name: Daily HuggingFace Data Ingestion

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.9'

jobs:
  ingest_and_upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests lxml datasets huggingface_hub

    - name: Run data ingestion script and upload to Hugging Face
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
        HF_REPO_ID: 'user/ingest' 
      run: |
        python hf_ingest.py

    - name: Clean up local data.csv (Optional, if created)
      run: |
        rm -f data.csv
